- hosts: k8s_cluster[0]
  tasks:
    - name: check param
      fail:
        msg: Cannot have both kubeconfig_localhost and create_oidc_kubeconfig set.
      when:
        - kubeconfig_localhost | default(false)
        # - create_oidc_kubeconfig | default(false)

- hosts: k8s_cluster
  roles:
    - role: kubespray-defaults
      when:
        # - create_oidc_kubeconfig
        - inventory_hostname == groups['kube_control_plane'][0]
  tasks:
    - name: Move cluster admin kubeconfig
      command: mv "{{ artifacts_dir }}/admin.conf" "{{ artifacts_dir }}/{{ kubeconfig_file_name }}"
      delegate_to: localhost
      become: false
      run_once: true
      args:
        removes: "{{ artifacts_dir }}/admin.conf"
      when:
        - kubeconfig_localhost
